services:
  app:
    build: .
    container_name: whim-app
    restart: unless-stopped

    volumes:
      - ./db:/app/db # Database volume

    env_file:
      - .env

    ports:
      - 3000:3000

  caddy:
    image: caddy:alpine
    container_name: whim-caddy
    restart: unless-stopped

    cap_add:
      - NET_ADMIN

    ports:
      - 80:80
      - 443:443
      - 443:443/udp

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
