services:
  app:
    build: .
    container_name: whim-app
    restart: unless-stopped
    volumes:
      - ./db:/app/db # Database volume
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - whimnet

  caddy:
    image: caddy:alpine
    container_name: whim-caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy-configs:/etc/caddy/configs
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - umami
    networks:
      - whimnet

  umami:
    container_name: umami
    image: docker.umami.is/umami-software/umami:postgresql-latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${UMAMI_DATABASE_URL}
      APP_SECRET: ${UMAMI_APP_SECRET}
    ports:
      - 3001:3000
    networks:
      - whimnet

  umami-db:
    container_name: umami-db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${UMAMI_DB_NAME}
      POSTGRES_USER: ${UMAMI_DB_USER}
      POSTGRES_PASSWORD: ${UMAMI_DB_PASSWORD}
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    networks:
      - whimnet

volumes:
  caddy_data:
  caddy_config:
  umami-db-data:

networks:
  whimnet:
    driver: bridge
