/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhimIdRouteImport } from './routes/$whimId'
import { Route as IndexRouteImport } from './routes/index'

const WhimIdRoute = WhimIdRouteImport.update({
  id: '/$whimId',
  path: '/$whimId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$whimId': typeof WhimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$whimId': typeof WhimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$whimId': typeof WhimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$whimId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$whimId'
  id: '__root__' | '/' | '/$whimId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhimIdRoute: typeof WhimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$whimId': {
      id: '/$whimId'
      path: '/$whimId'
      fullPath: '/$whimId'
      preLoaderRoute: typeof WhimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhimIdRoute: WhimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
